### ISSUE TITLE
Add default destination configuration when ommited

### ISSUE THREAD

**Issue by iamandrewluca** [kachkaev/njt#151]
I'm using njt most of the time just to jump to the repository.
And I have always to type

```
njt react g
```

Would be good to have some configuration in web, that you can set for example default destinatio to `g` and jsut write

```
njt react
```

Possible ways to implement it

- manually set a default destination
- jump to last used destination
- use most used destination

ps: I might start a PR soon.

**Comment by kachkaev** [comment]
Hmm not sure how to do this in a backwards-compatible way TBH 🤔 `njt react` means → https://www.npmjs.com/package/react and changing that can be confusing.

Some CI commands have `-` as an alias to ‘previous’, e.g. `cd -` moves you back to the last visited folder and `git switch -` takes you to the last checked out branch. In theory, we could implement `njt react -` to go to the last visited destination, but I don’t see much value in this TBH. Typing `njt react -` would take as much time as `njt react g`, but would be less predictive because of its statefullnes.

If you want to cut the number of chars, you can replace `njt react g` with `n react g` – that’s as long as `njt react`. See _Pro tips_ [in README](https://github.com/kachkaev/njt) for details.

Having said the above, I’m open to more ideas 🙂

**Comment by iamandrewluca** [comment]
I mean this to be only in the web UI.
User opens https://njt.vercel.app/ clicks a checkbox with the option. And we can persist it in a cookie.

**Comment by iamandrewluca** [comment]
Actually. I think this can be reproduced with browser search engine. Let me check

**Comment by iamandrewluca** [comment]
easy peasy lemon squeezy with a bookmarklet :)

https://gist.github.com/iamandrewluca/4184e0700e7c50a81e9c15daa63684cf

Put this in "Query URL" of the search engine

```
javascript: void ((function(query) {
  /* More bookmarklets at https://gist.github.com/iamandrewluca/61feacf07bc4f2f50e70f986c2e9b2d2 */
  const [packageName, destination = 'g'] = query.split(' ');
  window.location.href = `https://njt.vercel.app/jump?to=${packageName} ${destination}`;
})('%s'));
```

**Comment by kachkaev** [comment]
Nice!

Here’s one more thing we can do to the web UI in theory. Imagine that the query is persisted in the local storage, so when the page reloads, you see what you’ve typed in the last time. A single click on the input selects everything, but a double-click selects only a given word. So this scenario becomes possible:

![Kapture 2021-09-02 at 12 18 39](https://user-images.githubusercontent.com/608862/131834767-52f11f2e-613a-4d8a-b7ba-87b66a4e48a9.gif)

Double-click does not work for multi-word package names like `react-query` or `@types/react` out of box, but it might be possible to override the default event handler to fix that.
