### ISSUE TITLE
Privacy policy: add to README.md and/or website

### ISSUE THREAD

**Issue by mrienstra** [kachkaev/njt#175]
Currently, there is nothing (that I could find) stating if any data is collected on <https://njt.vercel.app/> during use, whether beginning there or just hopping through from CLI or browser extension (etc.), and what will and will not be done with said data.

I'm imagining that's because no data is collected -- aside from the boring goes-without-saying side effect of hosting / DNS / etc. -- but it would be nice to make that explicit.

_Additional keywords: tracking, analytics, google, targeted ads, data broker_

**Comment by kachkaev** [comment]
👋 @mrienstra! Good point about privacy, I haven’t thought of writing it up before. WDYT of https://github.com/kachkaev/njt#privacy I’ve just [added](https://github.com/kachkaev/njt/commit/fa34f7c99a17dd063ed9aa66ea545bbbeddd598a)?

Happy to elaborate on the topic a bit more if necessary. Otherwise, feel free to close this issue.

**Comment by mrienstra** [comment]
That's great, thanks!
