### ISSUE TITLE
Add support for changelog by other names

### ISSUE THREAD

**Issue by Siilwyn** [kachkaev/njt#7]
Instead of getting a 404 response it would be nice to try the following names since not all projects use `CHANGELOG.md`, I come across:
- `changelog.md` (lowercase)
- `CHANGELOG`
- `changelog`

**Comment by kachkaev** [comment]
👋 @Siilwyn thanks for this issue! I see your improvement suggestion as a special case of a wider problem, which is in the variety of repo configs. People can have different main branches, not just the file names. To know what URL to for changelog to open, njt would need to ask GitHub to provide some data about the repo first. This will involve some njt ←→ Github API interaction instead of this hardcoded logic:

https://github.com/kachkaev/njt/blob/94517ca8b99e5d9e607a417b172a28d98c807821/src/shared/destinations.ts#L80-L87

I'd like to address this at one point, but don't have enough capacity at the moment. I'd be happy to accept a PR though 🙂

**Comment by Siilwyn** [comment]
Ah I see the bigger problem, what about as a small improvement checking multiple URLs?
Since the function is async it could fetch the most common changelog locations to see if one of them returns a 200 response.

**Comment by iamandrewluca** [comment]
A PR is open for this feature!

**Comment by kachkaev** [comment]
Thanks to a contribution by @iamandrewluca, njt now supports non-standard CHANGELOG names in GitHub repos 🎉 

If anyone comes across a package hosted on GitLab, BitBucket or elsewhere with a non-standard CHANGELOG file name, feel free to ping here and we'll reopen the issue.
